
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: public_user
      POSTGRES_PASSWORD: publicN3xt!
      POSTGRES_DB: public_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: public_user
      MONGO_INITDB_ROOT_PASSWORD: publicN3xt!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq


volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  rabbitmq_log:
