scrape_configs:
  - job_name: 'orders-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Orders-Microservice'

  - job_name: 'logging-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    scheme: http
    static_configs:
        - targets: ['host.docker.internal:8081']
          labels:
            application: 'Logging-Microservice'

