{
 "title": "Cache Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Cache Total Hits/Misses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_gets_total{cache=\"orders\",result=\"hit\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cache_gets_total{cache=\"orders\",result=\"miss\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Cache Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{cache=\"orders\"}[60m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(cache_puts_total{cache=\"orders\"}[60m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(cache_removals_total{cache=\"orders\"}[60m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Cache Miss Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{cache=\"orders\",result=\"miss\"}[60m])) / sum(rate(cache_gets_total{cache=\"orders\",result=~\"hit|miss\"}[60m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Cache Hit Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{cache=\"orders\",result=\"hit\"}[60m])) / sum(rate(cache_gets_total{cache=\"orders\",result=~\"hit|miss\"}[60m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}