{
 "title": "Custom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processing Time Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(orders_processing_time_seconds_sum[5m])/rate(orders_processing_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Value Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(orders_value_bucket[1h])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Processing Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(orders_processing_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Status Distribution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_monthly_status", "legendFormat": "{{status}}" }
   ]
  }
 ]
}