{
 "title": "Orders Microservice Logs Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Rate Bar Gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"spring-boot-logs\"} |= \"ERROR\" [5m]))"
    }
   ]
  },
  {
   "title": "Error Logs over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"spring-boot-logs\"} |~ \"(?i)error\"[1m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spring-boot-logs\"}"
    }
   ]
  }
 ]
}