drop table if exists app_users;
drop table if exists order_lines_aud;
drop table if exists orders_aud;
drop table if exists order_lines;
drop table if exists orders;


create table if not exists app_users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255) not null,
    role     varchar(255) not null,
    username varchar(255) not null
        constraint ukspsnwr241e9k9c8p5xl4k45ih
            unique
);


create table if not exists orders
(
    id                     bigint generated by default as identity
        primary key,
    created_date           timestamp(6),
    last_modification_date timestamp(6),
    customer_name          varchar(255) not null,
    order_date             date         not null,
    order_id               varchar(255) not null
        constraint ukhmsk25beh6atojvle1xuymjj0
            unique,
    order_status           varchar(255) not null
);


create table if not exists order_lines
(
    id                     bigint generated by default as identity
        primary key,
    created_date           timestamp(6),
    last_modification_date timestamp(6),
    price                  double precision not null,
    product_id             varchar(255)     not null,
    quantity               integer          not null,
    order_id               bigint
        constraint fk1smc0s578t2oih21yn9hw6usr
            references orders
);


create table if not exists revinfo
(
    rev      integer not null
        primary key,
    revtstmp bigint
);

create table if not exists orders_aud
(
    id           bigint  not null,
    rev          integer not null
        constraint fkinujab7ljkelflu16c9jjch19
            references revinfo,
    revtype      smallint,
    order_status varchar(255),
    primary key (rev, id)
);


create table if not exists order_lines_aud
(
    id       bigint  not null,
    rev      integer not null
        constraint fkdxs1lpyhdf7qm723fcglfd490
            references revinfo,
    revtype  smallint,
    price    double precision,
    quantity integer,
    order_id bigint,
    primary key (rev, id)
);

