server:
  http_listen_port: 9080
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-logs
          __path__: /var/log/spring-boot.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})\s+\[(?P<thread>.*?)\]\s+(?P<level>\w+)\s+(?P<logger>.*?)\s+-\s+(?P<message>.*)'
      - labels:
          level:
          thread:
          logger: